# MCU name
MCU = atmega32u4

# Bootloader selection
BOOTLOADER = caterina

SPLIT_KEYBOARD = yes
SWAP_HANDS_ENABLE = no

ENCODER_ENABLE = yes
OLED_ENABLE = yes
OLED_DRIVER = SSD1306

RGBLIGHT_ENABLE = yes
WPM_ENABLE = yes
SLEEP_LED_ENABLE = no  

LTO_ENABLE = yes
MOUSEKEY_ENABLE = no
EXTRAKEY_ENABLE = yes
CONSOLE_ENABLE = no
MAGIC_ENABLE = no
SPACE_CADET_ENABLE = no